from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class DocumentProfile:
    name: str
    target_entities: str
    target_relations: str
    inventory_entities_per_chunk: str
    relations_per_chunk: str
    focus: tuple[str, ...] = field(default_factory=tuple)
    avoid: tuple[str, ...] = field(default_factory=tuple)
    preferred_entity_types: tuple[str, ...] = field(default_factory=tuple)
    preferred_relation_labels: tuple[str, ...] = field(default_factory=tuple)
    preferred_attribute_keys: tuple[str, ...] = field(default_factory=tuple)
    postprocess_deny_terms: tuple[str, ...] = field(default_factory=tuple)

    def prompt_block(self) -> str:
        focus = "\n".join(f"  - {item}" for item in self.focus) or "  - Core stable knowledge entities and explicit relations."
        avoid = "\n".join(f"  - {item}" for item in self.avoid) or "  - Temporary, vague, or sentence-like facts."
        return (
            "Document-specific strategy:\n"
            f"- Strategy name: {self.name}\n"
            f"- Final target scale: about {self.target_entities} entities and {self.target_relations} relations for this document.\n"
            f"- Inventory target: {self.inventory_entities_per_chunk} entities per information-rich chunk.\n"
            f"- Relation target: {self.relations_per_chunk} relations per information-rich chunk.\n"
            "- Platform feedback rule: once the target scale and core anchors are covered, stop expanding low-confidence details; preserve score-proven mixed naming instead of over-normalizing.\n"
            "- Focus on:\n"
            f"{focus}\n"
            "- Avoid:\n"
            f"{avoid}"
        )


DEFAULT_ZH_PROFILE = DocumentProfile(
    name="balanced_zh",
    target_entities="45-110",
    target_relations="35-95",
    inventory_entities_per_chunk="14-26",
    relations_per_chunk="8-16",
    focus=(
        "核心主题实体、分类体系、阶段过程、人物/组织/地点、作品/事件、技术/机制、指标、方法、应用场景。",
        "明确出现的缩写、标准、型号和稳定概念。",
        "优先让核心实体形成直接关系；短属性用于补充别名、全称、功能、用途、时期、地点、代表例子。",
    ),
    avoid=(
        "临时状态、口语化评价、背景铺垫、泛化目标。",
        "把长句、阈值描述、表格说明、活动通知、教学问答或干扰文本当实体。",
    ),
    preferred_entity_types=("概念", "技术", "系统", "组件", "指标", "流程", "方法", "应用场景"),
    preferred_relation_labels=("包含", "用于", "应用于", "影响", "驱动", "依赖", "支持", "导致"),
    preferred_attribute_keys=("别名", "全称", "功能", "用途", "特点", "应用场景", "标准"),
)

DEFAULT_EN_PROFILE = DocumentProfile(
    name="balanced_en",
    target_entities="30-75",
    target_relations="24-65",
    inventory_entities_per_chunk="10-20",
    relations_per_chunk="7-14",
    focus=(
        "Core topic entities, category systems, stages, people, organizations, locations, works, events, mechanisms, methods, applications, and stable categories.",
        "Prefer direct relations among core entities; use short attributes for alias, full_name, function, role, period, example, location, or source.",
    ),
    avoid=(
        "Loose background statements, generic plural phrases, sentence-like entities, teaching prompts, dates, notices, and distractor text.",
        "Long description attributes.",
    ),
    preferred_entity_types=("concept", "technology", "component", "process", "organization", "person", "location"),
    preferred_relation_labels=("contains", "is_part_of", "affects", "drives", "supports", "used_for", "applies_to"),
    preferred_attribute_keys=("alias", "full_name", "function", "role", "type", "example", "location"),
)


PROFILES: dict[str, DocumentProfile] = {
    "1": DocumentProfile(
        name="file1_3c_manufacturing_precision",
        target_entities="38-45",
        target_relations="22-26",
        inventory_entities_per_chunk="28-42",
        relations_per_chunk="14-22",
        focus=(
            "这是短篇 3C 制造质量管理文档，应抽成一张完整但精炼的制造质量图。",
            "核心锚点必须尽量覆盖：3C产品、研发部门、工业设计团队、BOM、ECR/ECO、SMT贴装PCB、回流焊、AOI自动光学检测、功能测试(FCT)、老化测试(Aging Test)、FPY、IFIR、OOB、RA、PSI、5Why、鱼骨图、8D、贴片机、回流焊炉、测试设备、老化柜、MES、QMS、ERP、PLM、数据中台、制造知识图谱。",
            "实体优先覆盖 8 类主干：3C产品、研发/设计部门、BOM与工程变更、制造工序、质量指标、不良分析方法与不良类型、设备/维护、MES/QMS/ERP/PLM/数据中台/制造知识图谱。",
            "缩写实体优先使用短 canonical 名称：BOM、MES、QMS、ERP、PLM、FPY、IFIR、OOB、RA、PSI；中文全称、英文全称、别名放入 attributes，不要把全称括在 name 里。",
            "需要保留中层归纳实体作为关系中心，例如 3C产品、工艺、设备、质量指标、不良分析与问题追溯、信息系统与数据管理、3C制造、制造知识图谱。",
            "制造工序重点保留 SMT 贴装 PCB、回流焊、AOI 自动光学检测、功能测试(FCT)、老化测试(Aging Test)、测试设备、老化柜等能形成关系的节点。",
            "关系优先抽职责/触发/影响/包含/用于/负责/管理/分析/监控/关联/应用于，不要只抽包含。",
            "属性优先补职责、工作内容、功能、别名、全称、典型示例、计算依据、演进方向，值要短。",
        ),
        avoid=(
            "不要把智能手机、笔记本电脑、平板设备、可穿戴终端拆成多个产品实体；它们更适合作为 3C产品 的典型示例属性。",
            "不要把产品型号、生产线、工站、设备编号、操作员、批次、供应商全部拆成大量孤立追溯实体；优先作为 不良分析与问题追溯 或 不良现象 的短属性。",
            "不要抽投入数、产出数、不良数、设备状态、测试结果等低层数据项为实体，除非它们形成核心关系。",
            "不要输出 BOM 包含生产工序 这类错误关系；BOM 描述零部件构成并影响采购、制造、质量控制和生产线配置。",
            "不要输出 ECR/ECO 触发 BOM变更；方向应是 BOM变更 触发 ECR/ECO，或 BOM 触发 ECR/ECO。",
            "不要生成 关键质量指标变更 这类原文没有的实体。",
            "不要保留表格、页码、emoji、背景口号、泛泛的数字化转型叙述。",
        ),
        preferred_entity_types=("质量指标", "信息系统", "分析方法", "生产设备", "部门", "制造工序", "产品", "不良现象"),
        preferred_relation_labels=("包含", "关联", "分析", "应用于", "用于", "负责", "管理", "触发", "影响"),
        preferred_attribute_keys=("全称", "别名", "功能", "用途", "示例", "主要职责", "工作内容", "阶段"),
    ),
    "2": DocumentProfile(
        name="file2_notebook_test_system",
        target_entities="35-39",
        target_relations="26-30",
        inventory_entities_per_chunk="18-28",
        relations_per_chunk="10-16",
        focus=(
            "这是笔记本电脑测试体系白皮书，应抽成测试体系图，不是硬件组成图。",
            "核心锚点必须尽量覆盖：笔记本电脑测试、处理器、主板、内存、固态硬盘、Prime95、AIDA64、MemTest86、CrystalDiskMark、IOMeter、PCMark、3DMark、Geekbench、校色仪、POST测试、性能测试、功耗测试、续航测试、散热测试、可靠性测试、软件测试、兼容性测试、安全测试、功耗分析仪、环境温度、环境参数、测试工程师、测试人员、硬件测试工程师、硬件设计工程师、质量管理人员、ISO 9001、TPM模块、测试报告、自动化测试平台、数据分析系统、测试流程。",
            "实体优先覆盖测试领域/测试流程、测试工具、测试角色、关键硬件测试对象、质量标准和环境参数。",
            "关系优先抽 执行/验证/应用于/影响/包含/反馈至/遵循，不要把 测试工具、性能测试工具、标准 这类名词当关系标签。",
            "属性优先补测试重点、用途、功能、职责、关键指标、影响因素、覆盖范围，值要短。",
        ),
        avoid=(
            "不要把笔记本电脑的所有组成部件都抽成关系中心；电池、显卡、无线网卡、键盘、触控板、散热系统如果缺少测试关系可不抽。",
            "不要把 USB接口、HDMI接口、雷电接口、打印机、扩展坞、办公软件等外设/接口清单展开为实体。",
            "不要保留乱码、emoji、白皮书标题、测试条件清单中的操作系统版本/驱动版本/电源模式等孤立实体。",
            "不要输出 处理器-测试工具-Prime95、ISO 9001-标准-安全与质量管理 这类名词关系。",
        ),
        preferred_entity_types=("测试工具", "测试流程", "硬件组件", "测试角色", "测试领域", "环境参数", "质量标准"),
        preferred_relation_labels=("执行", "应用于", "包含", "验证", "影响", "反馈至", "遵循"),
        preferred_attribute_keys=("功能", "测试重点", "职责", "用途", "测试指标", "关键指标", "覆盖范围"),
    ),
    "3": DocumentProfile(
        name="file3_notebook_architecture_precision",
        target_entities="26-28",
        target_relations="18-20",
        inventory_entities_per_chunk="14-22",
        relations_per_chunk="7-11",
        focus=(
            "这是笔记本电脑硬件架构文档，应抽成硬件架构主干图。",
            "核心锚点尽量覆盖：笔记本电脑、中央处理器（CPU）、图形处理单元（GPU）、主板、Intel、AMD、NVIDIA、芯片组、内存子系统、NVMe SSD、M.2接口、PCIe、显示子系统、显示屏、eDP、触控板、I2C、电源管理系统、USB Power Delivery、散热系统、热管、结构件系统、铝合金、Thunderbolt、DisplayPort、BIOS、UEFI。",
            "关系优先抽：包含、制造、连接、通信于、基于、支持、集成、控制。",
            "属性优先补架构、通信总线、协议、接口、组成、材料、功能、常见厂商。",
        ),
        avoid=(
            "不要把数据通信、数据存储、用户交互、电压调节、电流分配、能耗、整机稳定性、机身制造等泛概念作为实体。",
            "不要展开所有接口和材料，只保留文中关键关系需要的 PCIe、M.2接口、eDP、I2C、Thunderbolt、DisplayPort、USB Power Delivery、铝合金。",
            "不要抽 SATA SSD、HDD、USB-A、USB-C、HDMI、音频接口等边缘清单项，除非形成关键关系。",
        ),
        preferred_entity_types=("硬件组件", "子系统", "接口协议", "制造厂商", "技术标准", "固件程序", "材料"),
        preferred_relation_labels=("包含", "制造", "基于", "连接", "通信于", "集成", "支持", "控制"),
        preferred_attribute_keys=("功能", "别名", "通信总线", "设计", "组成", "标准", "协议"),
    ),
    "4": DocumentProfile(
        name="file4_gpu_card_architecture_precision",
        target_entities="48-58",
        target_relations="36-46",
        inventory_entities_per_chunk="40-58",
        relations_per_chunk="30-44",
        focus=(
            "这是显卡/GPU 架构科普文档，应抽成 GPU 硬件架构、芯片设计制造、板级供电散热、软件驱动的主干图。",
            "核心锚点必须尽量覆盖：显卡、GPU、GPU架构、SIMT架构、计算单元、SM（Streaming Multiprocessor）、CU（Compute Unit）、ALU（算术逻辑单元）、Warp 调度器、Wavefront调度、专用模块、纹理单元（Texture Unit）、Rasterizer（光栅化单元）、ROP（Render Output Unit）、RT Core（光线追踪核心）、Tensor Core、显存系统、显存（VRAM）、显存类型、GDDR6、GDDR6X、HBM（高带宽内存）、显存带宽、显存控制器、RTL设计、Verilog、SystemVerilog、综合、门级电路、时序分析、布局布线、制程节点（Process Node）、封装、Flip-Chip封装、2.5D封装、PCB、VRM（Voltage Regulator Module）、MOSFET、电感、电容、散热系统、散热片、热管、风扇、均热板、驱动程序、API、DirectX、Vulkan、CUDA。",
            "关系优先抽结构包含、流程顺序、模块功能和接口翻译：包含、用于、控制、连接、影响、依赖、执行、映射至、应用于、翻译、决定、支持。",
            "属性优先补全称、别名、功能、组成、常见类型、示例、设计目标、关键指标，值要短，不要写成长句。",
        ),
        avoid=(
            "不要把口语化解释、比喻或句子片段当实体，例如 喂数据的速度、GPU 被饿着跑、把逻辑描述出来、良率低了基本就是在烧钱。",
            "不要把游戏帧率高不高、跑 AI 推理快不快、最高能跑多快、买回家爽跑等表达抽成实体。",
            "不要把性能、功耗、面积、成本、发热、频率等孤立指标过度展开；只有和制程/布局布线/GPU架构形成明确关系时才保留。",
            "不要输出 全称、标准、组件、设计语言 这类类型词作为关系标签。",
        ),
        preferred_entity_types=("硬件组件", "计算单元", "专用模块", "显存技术", "设计流程", "制造工艺", "封装技术", "板级组件", "散热组件", "软件接口"),
        preferred_relation_labels=("包含", "用于", "控制", "连接", "影响", "依赖", "执行", "映射至", "应用于", "翻译", "决定", "支持"),
        preferred_attribute_keys=("功能", "别名", "全称", "组成", "常见类型", "示例", "设计目标", "关键指标"),
    ),
    "5": DocumentProfile(
        name="file5_memory_llm_precision",
        target_entities="58-64",
        target_relations="50-56",
        inventory_entities_per_chunk="14-24",
        relations_per_chunk="8-14",
        focus=(
            "这是内存技术与产业链综述，应让模型抽出技术主干，而不是企业清单或泛趋势图。",
            "当前平台最优形态约为 61 个实体、54 条关系、49 个有属性实体；不要回到旧版 73 实体/64 关系的应用清单扩张。",
            "实体优先级最高：SRAM、DRAM、NAND Flash、DDR4、DDR5、LPDDR5X、GDDR6、HBM、HBM3E、TSV、CoWoS、3D NAND、SLC、MLC、TLC、QLC、SSD、企业级 SSD、SSD控制器、FTL、LDPC、垃圾回收、磨损均衡、UFS、CXL、CXL.memory、JEDEC、EUV 光刻、ArF 浸没式光刻、ALD、CVD、CMP、晶圆测试、封装测试。",
            "DRAM 可靠性与结构要优先抽：感应放大器、字线控制单元、刷新操作、ECC、Retention、Row Hammer。1T1C 可作为 DRAM 属性，不要强行拆成孤立实体。",
            "NAND/SSD 可靠性机制要优先抽：原始误码率、读干扰、写放大、程序/擦除循环、坏块管理、掉电保护、QoS 调度、介质健康度监控。只抽正文明确出现并能形成关系的项。",
            "关系优先抽强显式技术关系：包含、集成于、服务于、应用于、依赖于、演进为、影响、受制于、驱动、优化、制定、用于。重点覆盖 NAND Flash 演进为 SLC/MLC/TLC/QLC，Retention 影响刷新操作，Row Hammer 影响 DRAM，SSD控制器包含 FTL/垃圾回收/磨损均衡，LDPC 服务于企业级 SSD/TLC/QLC。",
            "应用场景只保留数据中心、AI 服务器、智能手机、汽车电子、高性能计算平台等核心场景；如果场景会挤掉技术机制实体，优先保留技术机制。",
            "属性优先补短事实：全称、别名、功能、特性、应用场景、关键技术、核心单元、风险、影响对象。属性值必须短，不写长解释。",
        ),
        avoid=(
            "不要把 Samsung、SK hynix、Micron、Kioxia、Western Digital、长江存储、长鑫存储、TSMC 等厂商作为主要增量；此前厂商扩展评分下降。",
            "不要把位线、行译码、列译码、预充电电路、I/O PHY、时钟树等低层清单全部展开；除非它们在片段中形成明确关系。",
            "不要抽泛化趋势和句子式实体，例如 系统表现、数据基础设施、技术环节、用户体验、量产能力、成本曲线和竞争壁垒。",
            "不要展开应用清单或市场趋势端点，例如 数据库、对象存储、训练集缓存、日志系统、价格弹性、兴趣增强、需求上行、交付节奏。",
            "不要把长句、枚举列表、市场叙述、知识图谱任务说明当实体。",
        ),
        postprocess_deny_terms=("用户体验", "系统表现", "数据基础设施", "技术环节", "量产能力", "成本曲线", "竞争壁垒", "价格弹性", "兴趣增强", "需求上行"),
        preferred_entity_types=("存储器件", "系统模块", "应用场景", "封装技术", "制造工艺", "标准协议", "计算硬件", "测试环节"),
        preferred_relation_labels=("服务于", "包含", "集成于", "应用于", "驱动", "依赖于", "优化", "用于", "演进为", "影响"),
        preferred_attribute_keys=("功能", "应用场景", "标准", "别名", "全称", "特性", "类型", "应用", "优势", "关键指标"),
    ),
    "6": DocumentProfile(
        name="file6_ssd_engineering_llm_precision",
        target_entities="152-162",
        target_relations="180-195",
        inventory_entities_per_chunk="16-26",
        relations_per_chunk="30-46",
        focus=(
            "这是 SSD 工程系统长文，应抽成 SSD 技术、固件、可靠性、接口、制造测试、应用场景和安全运维的高召回主干图。",
            "当前平台最优形态约为 157 个实体、189 条关系、135 个有属性实体；该文件是全数据集中少数关系召回优先的例外，不要压成短图。",
            "核心实体必须优先覆盖：SSD、NAND Flash、NAND、3D NAND、SLC、MLC、TLC、QLC、伪SLC缓存、主控芯片、控制器、SSD控制器、FTL、FTL策略、GC、垃圾回收、磨损均衡、ECC、LDPC、BCH、分层数据保护体系、DRAM、DRAM-less方案、HMB、PLP、掉电保护、NVMe、AHCI、PCIe、PCIe Gen5、ONFI、Toggle、ZNS、ZNS (Zoned Namespace)、SMART遥测、TBW、DWPD、P/E Cycle、写放大、写放大系数、尾时延、QoS、Over-Provisioning。",
            "制造与测试实体必须优先覆盖：晶圆制造、封装测试、板级装配、板级制造、制造工艺、NAND颗粒、控制器芯片、固件版本、料号管理、颗粒混用策略、批次追溯、筛选验证、一致性管理、失效分析体系、Bring-up阶段、性能调优阶段、可靠性验证。",
            "安全与运维实体优先覆盖：AES/XTS、TCG Opal、Pyrite、安全擦除、密钥管理、管理接口、运维平台、温度遥测、温控节流、热设计、散热设计、热管理曲线、节流阈值。",
            "应用场景优先覆盖：数据中心、数据库、数据库日志、虚拟化平台、AI训练集群、AI训练场景、边缘计算、工业控制、车载系统、个人终端、对象存储缓存、数据湖、PS5、4K/8K视频剪辑。",
            "关系优先抽强显式技术关系：包含、使用、搭载、依赖、支持、采用、适配、用于、优化、影响、受限于、决定、保护、治理、表征、兼容。关系端点必须是短技术实体，不要用整句描述作为端点。",
            "属性优先补短事实：全称、别名、功能、特点、应用场景、关键指标、影响因素、形态规格、风险、适用场景。属性值必须短。",
        ),
        avoid=(
            "不要抽元知识：知识图谱、知识建模、工程复杂度、训练数据、专家思维。",
            "不要把泛化目标或宣传口号作为实体：极致性能、极致成本、极致可靠、热目标、成本目标、寿命目标、真实使用体验、参数崇拜。",
            "不要把长故障句或口语化解释作为实体：文件损坏、数据库页破坏、性能漂移、映射损坏、主控发热、跑久了掉速、虚标、买哪块盘最快。",
            "不要把条件判断整句作为实体，例如 在高温高填充度持续写入条件下尾延迟恶化风险增加；应拆成 QLC SSD、尾延迟、超配、GC策略 等短实体关系。",
            "不要输出 关联知识建模、影响工程复杂度、平衡SSD、讲清楚、真正专业的评估 这类弱关系或元关系。",
        ),
        postprocess_deny_terms=("知识图谱", "知识建模", "工程复杂度", "极致性能", "极致成本", "极致可靠", "热目标", "成本目标", "寿命目标", "文件损坏", "数据库页破坏", "性能漂移", "映射损坏", "参数崇拜", "专家思维"),
        preferred_entity_types=("技术指标", "应用场景", "管理策略", "软件系统", "硬件组件", "接口协议", "制造工艺", "存储介质"),
        preferred_relation_labels=("包含", "适配", "优化", "用于", "影响", "关联", "受限于", "治理", "决定", "导致"),
        preferred_attribute_keys=("功能", "类型", "特点", "全称", "影响因素", "别名", "影响", "作用", "目的", "核心功能"),
    ),
    "7": DocumentProfile(
        name="black_hole_reference_aligned",
        target_entities="82-98",
        target_relations="70-78",
        inventory_entities_per_chunk="18-28",
        relations_per_chunk="10-16",
        focus=(
            "黑洞长文应抽成精炼但属性充足的天体物理知识图谱；核心术语必须覆盖，但不要抽泛概念、类别词或说明短语。",
            "核心对象优先覆盖：黑洞、事件视界、史瓦西半径、史瓦西黑洞、恒星级黑洞、中等质量黑洞 (IMBH)、超大质量黑洞 (SMBH)、原初黑洞 (PBH)、人马座A*、M87*、天鹅座X-1、克尔黑洞、赖斯纳–诺德斯特伦黑洞、克尔–纽曼黑洞。",
            "核心机制和模型优先覆盖：引力坍缩、经典无毛定理、自旋、参考系拖拽、能层、彭罗斯过程、Blandford–Znajek 机制、吸积盘、夏库拉–苏尼亚耶夫盘模型、ADAF 模型、slim disk、最内稳定圆轨道、光子球、霍金辐射、贝肯斯坦–霍金熵、黑洞热力学、GRMHD、MRI。",
            "核心观测和辐射优先覆盖：EHT、LIGO、GW150914、引力波、黑洞阴影、阴影—亮环结构、活动星系核 (AGN)、类星体、Fe Kα 谱线、同步辐射、逆康普顿散射、SSC、准周期振荡、准正则模（QNM）、活动星系核反馈、奇点、黑洞信息悖论。",
            "实体命名要短且规范：优先使用 人马座A* (Sgr A*)、M87*、天鹅座X-1、活动星系核 (AGN)、类星体、广义相对论磁流体力学（GRMHD）、磁旋不稳定性（MRI）、自同步康普顿（SSC）、准正则模（QNM）。",
            "同时保留原文中明确出现的括号/别名实体形态，不要一律合并：天鹅座X-1（Cygnus X-1）、类星体 (quasar)、AGN feedback（活动星系核反馈）、霍金辐射 (Hawking radiation)、贝肯斯坦-霍金熵 (Bekenstein–Hawking entropy)、奇点（singularity）、ISCO（最内稳定圆轨道）、引力波 (gravitational waves)。",
            "观测源和证据实体必须优先覆盖：V404 Cygni、GRS 1915+105、A0620-00、GRO J1655-40、坍缩星、脉冲星、星系际介质、喷流、阴影、双黑洞并合、黑洞并合。",
            "关系优先抽属于、用于解释、产生、影响、导致、位于、限制、观测到、作为证据、包含；每个信息段抽 8-13 条高置信三元组，不要追求数量，不要用实体类型当关系谓词。",
            "关系端点优先来自实体清单；不要新增 中心黑洞质量、宿主环境、恒星形成率、较低能光子到更高能段、最终黑洞的质量和自旋密切相关 这类说明短语端点。",
            "属性是 7.md 的关键得分点：尽量为核心实体补短属性，如 别名、全称、定义、公式、位置、形成机制、适用条件、观测特征、相关概念、功能。",
        ),
        avoid=(
            "不要把长观测结论、公式条件、口语化解释作为实体。",
            "不要抽大众误解、写法提醒、语料清洗建议、下游模型提示、不是/不等价/不能简单认为 这类元叙述。",
            "不要把 明亮环、洞照片、黑色中心区域、某一整句观测描述 作为实体；应抽 黑洞阴影、阴影—亮环结构、EHT 图像。",
        ),
        preferred_entity_types=("天体物理对象", "物理概念", "物理模型", "观测现象", "物理参数", "辐射机制", "天体对象", "星系结构"),
        preferred_relation_labels=("属于", "用于解释", "产生", "包含", "影响", "导致", "位于", "相互作用", "限制"),
        preferred_attribute_keys=("别名", "类型", "功能", "相关概念", "位置", "定义", "特征", "全称", "观测特征"),
    ),
    "8": DocumentProfile(
        name="food_processing_precision",
        target_entities="44-50",
        target_relations="22-28",
        inventory_entities_per_chunk="16-24",
        relations_per_chunk="12-18",
        focus=(
            "食品加工长文应抽成高精度核心骨架，而不是高召回百科图谱；优先保留跨段主干实体、开篇框架实体和明确三元组端点。",
            "开篇框架需要保留：食品工业、谷物深加工、肉制品精制、Unit Operation（单元操作）。框架关系最多保留 食品工业-包含-谷物深加工、食品工业-包含-肉制品精制、谷物深加工-包含-Unit Operation（单元操作）；不要把所有后文技术点都挂到加工链条下面。",
            "小麦链条只抽核心端点：小麦、原粮、近红外光谱（NIR）、水分迁移速率、辊式磨粉机、筛理系统、灰分含量、淀粉损伤率、高筋粉生产。",
            "肉制品链条只抽核心端点：预冷、微生物、低温高剪切、盐溶性蛋白、磷酸盐类改良剂；不要抽分段冷却、盐添加顺序、pH、脂肪乳化失稳等细枝端点。",
            "乳制品链条只抽核心端点：巴氏杀菌、超高温瞬时灭菌（UHT）、乳清蛋白、乳酸菌、酸度曲线、乳制品加工；不要抽温度-时间组合、熟煮味、凝胶结构、后酸化速率。",
            "添加剂与包装冷链只抽核心端点：抗坏血酸、BHA、BHT、抗氧化剂、防腐剂、油脂体系、霉菌和酵母、多层共挤薄膜、改良气调包装(MAP)、致病菌、冷链管理、冷藏温度。注意 BHA/BHT 是抗氧化剂，关系目标应是油脂体系，不是防腐剂。",
            "质量与法规只抽核心端点：HACCP、HACCP（危害分析与关键控制点）、金属探测器、X射线异物检测系统、SCADA系统、SCADA系统（监控与数据采集系统）、MES、MES（制造执行系统）、质量控制体系、干燥工序、余热回收、微生物指标、李斯特菌、法规与标准、清洁标签。括号全称实体在原文出现时要保留为实体，不要只放到属性。",
            "主体关系必须是直接技术关系，不要用上位加工链条批量包含实体。关系阶段必须抽足 28-36 条高置信直接关系。优先抽：近红外光谱（NIR）-应用于-小麦、过程控制-优化-小麦、辊式磨粉机-影响-淀粉损伤率、预冷-抑制-微生物、低温高剪切-优化-盐溶性蛋白、筛理系统-决定-灰分含量、磷酸盐类改良剂-调节-盐溶性蛋白、巴氏杀菌/UHT-影响-乳清蛋白、乳酸菌-影响-酸度曲线、抗坏血酸/BHA/BHT/抗氧化剂-应用于-油脂体系、防腐剂-抑制-霉菌和酵母、改良气调包装(MAP)-抑制-致病菌、冷链管理/冷藏温度-导致-致病菌、HACCP-包含-金属探测器、SCADA系统-连接-MES、余热回收-优化-干燥工序、法规与标准-包含-微生物指标、李斯特菌-作为-微生物指标、清洁标签-影响-法规与标准。",
            "属性应短而有区分度：全称、别名、用途、关键参数、作用对象、控制指标、风险、典型成分；不要写长段说明。",
        ),
        avoid=(
            "不要把现代食品工业体系、复杂系统、终端质量、消费者接受度、资源利用率、产品矩阵等泛背景词作为核心实体。",
            "不要抽 OTR/WVTR、山梨酸钾、脱氢乙酸钠、在线粘度计、色差仪、蒸发工序、冷冻工序、酶法替代等细粒度点；上一轮实测这些点拉低分。",
            "不要把清洗、分级、粉碎、混合、热处理、冷却、包装等普通枚举步骤拆成实体。",
            "不要把完整阈值句、研究发现、企业行为、跨境贸易要求、法规差异描述作为实体或关系端点。",
            "不要中英文混写属性；中文文档用中文输出，英文缩写只作为原文术语保留。",
        ),
        postprocess_deny_terms=("消费者接受度", "断链风险", "过度粉碎"),
        preferred_entity_types=("加工工艺", "食品添加剂", "加工设备", "质量指标", "生产环节", "微生物", "质量控制体系", "食品原料"),
        preferred_relation_labels=("应用于", "影响", "包含", "优化", "抑制", "导致", "决定", "调节", "连接"),
        preferred_attribute_keys=("别名", "功能", "用途", "类别", "特点", "关键参数", "目的", "常见种类", "全称"),
    ),
    "9": DocumentProfile(
        name="wildlife_migration_relation_boost",
        target_entities="24-27",
        target_relations="14-17",
        inventory_entities_per_chunk="18-28",
        relations_per_chunk="16-24",
        focus=(
            "非洲动物迁徙文档应抽成物种-环境-捕食者-人类活动的直接生态关系图谱，不要抽成泛泛的生态系统说明。",
            "核心区域与系统：撒哈拉以南非洲、塞伦盖蒂—马赛马拉生态系统、恩戈罗恩戈罗保护区、非洲大草原、生态系统、迁徙通道。",
            "核心迁徙物种：角马、角马群体、斑马、汤姆森瞪羚、白鹳、草原鹨。物种属性优先放学名、食性、迁徙特征、栖息区域。",
            "核心捕食者：非洲狮、斑鬣狗、猎豹、鳄鱼、鳄鱼（尼罗鳄）。注意斑马和汤姆森瞪羚不是角马捕食者，只能与角马关联或共同迁徙。",
            "核心环境/气候/水文指标：降水带、ITCZ（赤道辐合带）、月均降水量、粗蛋白含量、归一化植被指数、NDVI（归一化植被指数）、降雨事件、昆虫、气候变化、马拉河。",
            "核心人类活动和干扰：人类活动、公路、围栏、定居点、动物可达性矩阵。",
            "关系优先抽直接生态谓词：驱动、限制、影响、关联、捕食、栖息于、依赖于、改变、迁徙路径、食性选择、作为、过河风险。不要用 长句、阈值句、概率句 做关系端点。",
            "应优先覆盖这些关系骨架：降水带-驱动-角马、月均降水量-限制-角马、角马-栖息于-塞伦盖蒂—马赛马拉生态系统、粗蛋白含量-影响-角马、斑马/汤姆森瞪羚-关联-角马、斑马-驱动-前驱放牧效应、非洲狮/斑鬣狗/猎豹-捕食-角马、马拉河-限制-角马、鳄鱼-栖息于-马拉河、气候变化-改变-归一化植被指数、归一化植被指数-影响-角马、白鹳/草原鹨-栖息于或依赖于-非洲大草原、降雨事件-驱动-昆虫、人类活动/公路/围栏/定居点-改变-迁徙通道或动物可达性矩阵。",
            "必须覆盖捕食关系：非洲狮-捕食-角马、斑鬣狗-捕食-角马、猎豹-捕食-角马；也可抽它们作为捕食者作用于角马群体。",
            "优先覆盖候鸟和跨营养级关系：白鹳-依赖于/栖息于-非洲大草原、草原鹨-栖息于-非洲大草原、降雨事件-驱动-昆虫。",
            "优先覆盖人类活动主干：公路/围栏/定居点-改变-动物可达性矩阵；不要为了追求数量强行补异常群体、食性植物或气候链条。",
            "评分反馈显示：食性选择、异常滞留群/提前折返群、气候变化链条在当前模型表达下会降低 precision；除非模型非常明确且端点短，否则不要抽这些扩展关系。",
        ),
        avoid=(
            "不要把 30mm、8%、受孕概率、幼体存活率、营养阈值、概率变化、模型描述和监测结论当实体。",
            "不要输出错误捕食关系：斑马 捕食 角马、汤姆森瞪羚 捕食 角马。",
            "不要把短雨季、早绿—快衰、随机游走、路径记忆失真、风险不确定性等现象过度展开为核心实体，除非作为关系端点很明确。",
            "不要主动抽食性选择、异常滞留群、提前折返群、气候变化链条；这些在上一轮平台反馈中降低了总分。",
        ),
        preferred_entity_types=("生物物种", "地理区域", "环境指标", "生态系统", "气候要素", "生态过程", "基础设施", "概念"),
        preferred_relation_labels=("栖息于", "改变", "影响", "驱动", "捕食", "迁徙路径", "限制", "关联", "食性选择"),
        preferred_attribute_keys=("别名", "学名", "功能", "特征", "影响", "现象", "地理范围", "迁徙模式", "行为特征"),
    ),
    "10": DocumentProfile(
        name="robotics_reference_aligned",
        target_entities="32-36",
        target_relations="16-20",
        inventory_entities_per_chunk="20-30",
        relations_per_chunk="8-14",
        focus=(
            "仿生机器人文档应抽成核心架构和应用主干，不要抽成泛泛的技术综述。",
            "当前平台最优形态约为 35 个实体、18 条关系、28 个有属性实体；关系要短而准，不要抽成 30+ 条模块清单。",
            "核心系统与层级：仿生机器人系统、仿生机器人、现代仿生机器人、仿生结构层、驱动与执行层、传感与感知层、控制与决策层、能量管理与通信层。",
            "标题层级实体不能被省略或只写成属性：仿生结构层、驱动与执行层、传感与感知层、控制与决策层、能量管理与通信层都应作为实体保留。",
            "核心驱动与执行：驱动装置、人工肌肉、介电弹性体驱动器、形状记忆合金、气动软执行器。关系优先是 用于/集成于 驱动与执行层。",
            "核心传感与感知：感知模块、视觉系统、仿生相机、触觉阵列、侧线传感器、事件驱动传感器、低功耗嵌入式处理器。关系优先是 包含/集成于 仿生机器人或传感与感知层。",
            "核心控制与决策：控制算法、模型预测控制、强化学习、自适应控制、分层控制架构、中央模式发生器（CPG）、中央模式发生器（CPG）模型。关系优先是 控制/实现/用于 仿生机器人或控制与决策层。",
            "核心能量和集成：锂电池、太阳能薄膜、模块化设计、数字孪生技术。关系优先是 用于 能量管理与通信层、依赖于 模块化设计、优化 仿生机器人。",
            "核心应用场景：医疗康复领域、灾害救援场景、海洋与空间探测、仿生外骨骼、蛇形机器人。关系优先是 应用于。",
            "必须覆盖架构关系：仿生机器人系统-包含-仿生结构层、仿生机器人系统-包含-感知模块、仿生机器人系统-包含-驱动装置、仿生机器人-包含-驱动与执行层、仿生机器人-包含-传感与感知层。",
            "必须覆盖控制关系：模型预测控制-控制-仿生机器人、强化学习-控制-仿生机器人、自适应控制-实现-仿生机器人、分层控制架构-实现-仿生机器人、中央模式发生器（CPG）-控制-仿生机器人。",
            "必须覆盖传感关系：仿生机器人-包含-仿生相机、仿生机器人-包含-触觉阵列、仿生机器人-包含-侧线传感器、事件驱动传感器-集成于-仿生机器人、仿生机器人-包含-低功耗嵌入式处理器。",
            "必须覆盖应用关系：仿生外骨骼-应用于-医疗康复领域、蛇形机器人-应用于-灾害救援场景、仿生机器人-应用于-海洋与空间探测、数字孪生技术-优化-仿生机器人。",
            "评分准则：优先短实体和直接关系，宁可少抽，不追伦理问题、安全问题、可靠性问题、未来趋势、材料科学、神经计算、人工智能方法等泛背景。",
        ),
        avoid=(
            "不要保留挑战/趋势/泛背景过多；不要用句子式关系。",
            "不要把 感知—认知—决策—执行闭环能力、数据驱动模型与机理模型的融合、群体智能与自组织行为的研究、完全复现其结构和功能 等长短语作为实体。",
            "不要把层级名和示例拼接成实体，例如 仿生结构层-骨骼—肌腱耦合结构；应保留短实体 仿生结构层，把示例放属性或不抽。",
            "不要主动抽伦理问题、安全问题、可靠性问题、软硬件协同设计、材料科学、神经计算、嵌入式系统、人工智能方法，除非模型能形成非常明确的短关系。",
            "不要把所有领域知识都挂到 仿生机器人 包含 X；包含只用于系统层级、模块和明确组成。",
        ),
        preferred_entity_types=("控制技术", "感知模块", "材料", "机器人系统", "核心组件", "应用领域", "设计方法", "概念"),
        preferred_relation_labels=("包含", "用于", "应用于", "控制", "实现", "集成于", "依赖于", "优化"),
        preferred_attribute_keys=("功能", "应用", "应用场景", "核心能力", "示例", "应用领域", "优势", "用途"),
    ),
    "11": DocumentProfile(
        name="oncology_clinical_midlevel_precision",
        target_entities="138-146",
        target_relations="54-60",
        inventory_entities_per_chunk="18-30",
        relations_per_chunk="18-28",
        focus=(
            "这是肿瘤治疗技术综述，应抽中层临床语义图谱，而不是药名百科或机制碎片清单。",
            "治疗主干必须覆盖：根治性切除术、解剖性肺叶切除、系统性淋巴结清扫、微创外科、术后辅助治疗、三维适形放疗（3D-CRT）、调强放疗（IMRT）、容积旋转调强（VMAT）、图像引导放疗（IGRT）、立体定向放疗（SBRT/SABR）、SBRT、近距离放疗、质子治疗、重离子/碳离子治疗、化疗、靶向治疗、免疫治疗、细胞治疗、CAR-T细胞治疗、TCR-T、TIL、抗体药物偶联物（ADC）、双特异性抗体、射频消融、微波消融、冷冻消融、不可逆电穿孔（IRE）、高强度聚焦超声（HIFU）、经导管动脉化疗栓塞（TACE）、肿瘤电场治疗（TTFields）、光动力治疗（PDT）、放射性核素治疗、内分泌治疗、抗血管生成治疗、支持治疗、姑息治疗。",
            "癌种和场景主干必须覆盖：实体瘤、非小细胞肺癌（NSCLC）、肺癌、结直肠癌、胃癌、乳腺癌、肝细胞癌、肝癌、头颈部肿瘤、前列腺癌、宫颈癌、早期肺癌、局部晚期直肠癌、晚期肺癌、黑色素瘤、肾癌、尿路上皮癌、三阴性乳腺癌、B细胞恶性肿瘤、胶质母细胞瘤、血液肿瘤、骨转移、骨相关事件、围术期创伤、术后辅助治疗、同步放化疗。",
            "标志物和检测监测主干必须覆盖：生物标志物、R0切除、微小残留病灶（MRD）、循环肿瘤DNA（ctDNA）、EGFR敏感突变、EGFR突变、EGFR-TKI、ALK融合、ROS1融合、MET外显子14跳读、RET融合、BRAF V600E、KRAS G12C、HER2扩增/过表达、HER2插入突变、HER2、RAS/BRAF状态、抗EGFR单抗、BRCA1/2、同源重组修复（HRR）异常、PARP抑制剂、PD-1/PD-L1抑制剂、PD-1、PD-L1、CTLA-4抑制剂、PD-L1—PD-1轴、PD-L1表达水平、MSI-H/dMMR、TMB、NGS、NGS动态监测、液体活检、组织活检、二次活检、RECIST标准、iRECIST。",
            "不良反应和风险主干必须覆盖：骨髓抑制、心脏毒性、放射性肺炎、放射性肠炎、免疫相关不良事件（irAE）、细胞因子释放综合征（CRS）、免疫效应细胞相关神经毒性综合征（ICANS）、脱靶毒性、毒性叠加、高血压、蛋白尿、出血、血栓、心血管风险、骨相关事件、中性粒细胞减少。",
            "关系优先抽中层强关系：治疗-适用于/用于治疗-癌种或场景，标志物-提示获益-治疗，治疗-导致/具有风险-不良反应，检测-监测-耐药/MRD/复发，治疗-联合使用-治疗，药物类别-适用于-癌种。",
            "高置信关系要优先覆盖：根治性切除术-适用于-实体瘤，系统性淋巴结清扫-联合使用-解剖性肺叶切除，循环肿瘤DNA（ctDNA）-提示获益-术后辅助治疗，SBRT-适用于-早期肺癌，近距离放疗-适用于-前列腺癌，化疗-导致-骨髓抑制/心脏毒性，粒细胞刺激因子-缓解-中性粒细胞减少，化疗-适用于-局部晚期直肠癌/晚期肺癌，EGFR-TKI-用于治疗-非小细胞肺癌，抗EGFR单抗-用于治疗-结直肠癌。",
            "支持治疗和骨转移关系要优先覆盖：双膦酸盐-用于治疗-骨相关事件，RANKL通路抑制剂-用于治疗-骨相关事件，5-HT3受体拮抗剂-用于治疗-止吐，造血生长因子-缓解-中性粒细胞减少。",
            "评估和试验关系要适度覆盖：RECIST标准-用于-影像学疗效评估，篮式试验-关联于-分子特征，伞式试验-关联于-分子亚型。不要把证据等级、指南共识、患者偏好、器官功能状态、可及性当核心实体。",
            "不要只输出上述示例关系；每个信息块仍需覆盖本块出现的治疗适应证、毒性、标志物获益、检测监测和联合治疗主干。",
            "靶向标志物必须连接对应靶向治疗，不要误连免疫治疗：EGFR敏感突变-提示获益-EGFR-TKI，BRCA1/2/同源重组修复（HRR）异常-提示获益-PARP抑制剂，RAS/BRAF状态-影响-抗EGFR单抗。PD-L1表达水平、MSI-H/dMMR、TMB 才优先连接免疫治疗或免疫检查点抑制剂。",
            "关系标签必须单一，不要输出 适用于/用于治疗、导致/具有风险、提示获益-治疗、监测-监测 这种复合标签。",
            "属性优先补别名、全称、用途、适用癌种、提示意义、典型风险、治疗阶段，值要短。",
        ),
        avoid=(
            "不要把整句临床判断、比喻、写作提醒、知识图谱构建建议作为实体。",
            "不要过度展开单个药品和过细毒性清单；顺铂、卡铂、奥沙利铂、紫杉醇、多西他赛可作为代表，但不要继续扩展大量药品。",
            "不要把 患者偏好、指南共识、证据等级、可及性、治疗窗口、概念热、名词爆炸、同名异义、拼写噪声 等泛管理词作为核心实体。",
            "不要把 AI结果、联合方案、病理与分子检测、器官功能状态 等泛约束词作为实体或关系端点。",
            "不要把电子病历、影像组学、病理切片、随访结局、实验室指标、患者报告结局等数据源大规模展开，除非形成明确检测/AI关系。",
            "不要输出 药物治疗癌症、治疗本身、节点之间的规则化连接 等元叙述关系。",
            "不要输出 EGFR/ALK/ROS1/MET/RET/BRAF/KRAS/HER2 这类靶向标志物 提示获益 PD-1/PD-L1抑制剂 或 CTLA-4抑制剂。",
        ),
        preferred_entity_types=("治疗技术", "肿瘤类型", "生物标志物", "不良反应", "临床检查", "治疗目标", "化疗药物"),
        preferred_relation_labels=("适用于", "用于", "用于治疗", "关联于", "提示获益", "导致", "联合使用", "监测", "缓解", "影响"),
        preferred_attribute_keys=("别名", "用途", "功能", "全称", "临床意义", "特点", "特征", "优势", "应用领域", "适用人群"),
    ),
    "12": DocumentProfile(
        name="corridor_logistics_midlevel_precision",
        target_entities="61-65",
        target_relations="66-70",
        inventory_entities_per_chunk="18-28",
        relations_per_chunk="18-30",
        focus=(
            "这是中东西线能源走廊运行纪要，应抽跨国物流、港口、能源、冷链、关务数据和应急保障的中层网络图，不是运行告警日志。",
            "核心走廊和文档实体：中东西线能源走廊、跨境节点联动日志、调度系统、调度节点、利雅得运营中心、迪拜南物流园、苏哈尔港、物流数据平台。",
            "国家/城市/港口/能源节点必须覆盖：沙特阿拉伯、利雅得、吉达港、达曼港、朱拜勒工业城、加瓦尔油田、东西原油管道、阿联酋、阿布扎比、扎库姆油田、杰贝阿里港、阿曼、苏哈尔港（SH）、杜库姆港（DQ）、卡塔尔、哈马德港、北方天然气田、科威特城、舒艾拜港、巴林集装箱码头、巴士拉、乌姆盖斯尔港、安曼、亚喀巴港、开罗、苏伊士运河、亚历山大港、伊斯坦布尔、杰伊汉港。",
            "中枢系统和保障实体必须覆盖：海合会关务数据平台、关务单证中心、自由贸易区节点、区域冷链追踪系统、吞吐量预测模型、预测引擎、卫星调度台、海水淡化补给网、粮食储备中心、应急燃料库、多式联运班列、维修备件中心、港机设备、SCADA、SCADA 终端、AIS、VTS、AIS 航迹校核。",
            "地理通道和货流实体优先覆盖：霍尔木兹海峡、波斯湾、阿拉伯海、红海、能源类货流、高时效货物、聚乙烯单元、LNG冷能回收装置。",
            "关系优先抽稳定中层谓词：调度、协同、监控、连接、服务于、配置、同步、触发、保障、属于、包含、位于、依赖于、影响。关系端点必须是短节点名，不要用整句条件。",
            "高置信关系包括：利雅得调度吉达港/达曼港/朱拜勒工业城/石化园区/粮食储备中心；加瓦尔油田影响东西原油管道，东西原油管道连接石化园区，石化园区包含聚乙烯单元；迪拜南物流园协同关务单证中心并同步区域冷链追踪系统/吞吐量预测模型；北方天然气田连接或服务于哈马德港；哈马德港配置LNG冷能回收装置；杜库姆港（DQ）触发苏哈尔港（SH）；巴林集装箱码头监控闸口峰值车流，闸口峰值车流触发二次搬移占比；杰伊汉港服务于能源类货流，伊斯坦布尔服务于高时效货物。",
            "补强保障链和区域外联：开罗协同苏伊士运河；亚历山大港协同粮食储备中心/海水淡化补给网并依赖吞吐量预测模型；区域冷链追踪系统服务于哈马德港/杰贝阿里港/亚喀巴港/舒艾拜港；海水淡化补给网服务于粮食储备中心；粮食储备中心协同应急燃料库/多式联运班列；应急燃料库保障多式联运班列；维修备件中心服务于港机设备/SCADA 终端。",
            "海合会关务数据平台、物流数据平台、区域冷链追踪系统、维修备件中心、卫星调度台是核心中枢，必须抽它们与港口/系统/设备的连接、服务、同步、监控关系。",
            "国家归属关系要保留：利雅得/吉达港/达曼港/朱拜勒工业城/加瓦尔油田/东西原油管道属于沙特阿拉伯；阿布扎比/杰贝阿里港/迪拜南物流园/扎库姆油田属于阿联酋；苏哈尔港（SH）/杜库姆港（DQ）属于阿曼；哈马德港/北方天然气田/LNG冷能回收装置属于卡塔尔。",
        ),
        avoid=(
            "不要抽批次号、窗口号、百分比、小时数、温度阈值、车次、版本号、脚注标记、乱码符号。",
            "不要把 08:00 前未完成 A-Loop 切换、聚乙烯库存只剩 21.6h、780 车次/2h、T-1 配载模板 等运行条件当实体。",
            "不要把 ETA、ETD、TEU、FEU、VLCC、ULCC、NGL 等缩写全展开为实体；除非形成核心关系，优先作为属性。",
            "不要过度抽箱区翻倒率、装卸偏差、泊位利用率、LNG冷能回收效率、堆高机可用度等短时运营指标，除非能形成明确 指标-影响-对象 关系。",
        ),
        postprocess_deny_terms=("批次", "窗口", "告警", "临时", "剩余", "未完成切换"),
        preferred_entity_types=("物流枢纽", "地理区域", "信息系统", "工业设施", "保障设施", "交通基础设施", "组织机构", "能源资源"),
        preferred_relation_labels=("属于", "服务于", "协同", "连接", "监控", "配置", "调度", "包含", "触发", "同步", "保障", "位于", "影响"),
        preferred_attribute_keys=("功能", "业务", "位置", "职能", "主要业务", "别名", "设施", "类别", "地理位置"),
    ),
    "13": DocumentProfile(
        name="global_energy_transition_macro_balanced",
        target_entities="60-66",
        target_relations="32-36",
        inventory_entities_per_chunk="14-22",
        relations_per_chunk="18-28",
        focus=(
            "这是全球能源转型综述，应抽宏观能源系统概念图：国际组织、政策工具、经济体、能源资源、基础设施、技术路线、市场机制、矿产供应链。",
            "13.md 的评分更偏宏观概念锚点，不要过度细化到所有国家和设施；允许保留 能源系统、全球能源系统、能源资源、基础设施、政策工具、技术路线、市场机制、经济体 这类上位节点，并用少量高置信关系连接。",
            "国际组织和治理节点必须覆盖：国际能源署（IEA）、政府间气候变化专门委员会（IPCC）、联合国气候变化框架公约（UNFCCC）、欧佩克（OPEC）、巴黎协定、COP28、国家自主贡献（NDC）。",
            "政策和市场机制优先覆盖：碳定价、财政激励、绿色金融、价格机制、欧盟碳排放交易体系（EU ETS）、碳边境调节机制（CBAM）、通胀削减法案（IRA）、容量市场、辅助服务市场。",
            "能源资源和技术路线优先覆盖：化石燃料、可再生能源、煤电、天然气、石油、LNG接收站、LNG液化厂、关键矿产、新能源项目、化工原料多元化、可持续航空燃料（SAF）、氢能、绿氢、蓝氢、CCUS、电解槽、核能、小型模块化反应堆（SMR）、水电、地热、生物质与生物燃料。",
            "基础设施和系统优先覆盖：能源系统、全球能源系统、电力系统、局部电网、电网、电网建设、新型电力系统、新型储能、高压直流输电（HVDC/UHV）、数据中心、电动汽车充电网络、数字化平台、综合能源服务。",
            "区域主体优先覆盖：中国、美国、欧盟、印度、德国、法国、发达经济体。其他国家/地区只有形成明确关系时再保留。",
            "关系优先抽宏观稳定谓词：影响、约束、调节、应用于、促使、驱动、构建、构筑、发布、推动、属于、依赖于、构成、替代。不要过度使用 发布/实施，如果原文是政策影响或驱动，可用 影响/驱动/促使。",
            "高置信关系包括：IEA/IPCC/UNFCCC 影响 能源系统；气候变化 约束 能源系统；可再生能源 替代 化石燃料；欧佩克（OPEC） 调节 石油；欧盟 发布 EU ETS；美国 发布 IRA；巴黎协定 驱动 欧盟；中国 构建 新型电力系统；新型储能 应用于 电力系统；辅助服务市场 调节 电力系统；可再生能源 影响 电力系统；数据中心 约束 局部电网；容量市场 调节 局部电网；绿氢 依赖 电解槽；蓝氢 依赖 CCUS；CCUS 应用于 水泥；SMR 属于 核能。",
            "不要只抽上述例子。每个信息丰富 chunk 应继续覆盖油气、矿产、氢能/CCUS、核能、电力系统、区域经济体、企业转型等关系，目标是每块 18-28 条高置信关系。",
            "列表端点仍要拆分，但不要为了拆分而抽过多细枝末节；优先宏观节点和可评分节点。",
        ),
        avoid=(
            "不要抽乱码片段、脚注标记、编号、百分比之外的杂字符，例如 �78&zxc#、�12&qwe&、�90&bnm&、�er78&、�ty56&、�ui89&、�op09&、�zx12&。",
            "不要把整句判断、趋势句、目标句、约束句抽成实体，例如 经济增长与能源安全的刚性需求、气候变化与减排承诺带来的约束、资源禀赋—基础设施—市场结构锁定效应。",
            "不要把泛化背景事件作为实体：国际关系变化、供应链中断、关键设备交付周期、利率水平、资本成本、汇率与贸易政策，除非它们形成明确政策/成本关系。",
            "不要让 能源系统、基础设施、经济体、政策工具、技术路线 这类上位概念连接所有实体；它们只在原文明确讨论框架时保留少量关系。",
            "不要用斜杠列表、顿号列表或长并列短语作为实体或关系端点；必须拆成短实体。",
        ),
        postprocess_deny_terms=("国际关系变化", "供应链中断", "关键设备交付周期", "汇率与贸易政策"),
        preferred_entity_types=("基础设施", "能源资源", "技术路线", "经济体", "政策工具", "国际组织", "市场机制", "概念"),
        preferred_relation_labels=("应用于", "影响", "约束", "调节", "应用", "替代", "促使", "驱动", "属于", "依赖"),
        preferred_attribute_keys=("功能", "别名", "作用", "状态", "职能", "组成", "驱动因素", "角色", "核心目标", "影响"),
    ),
    "14": DocumentProfile(
        name="english_energy_system_reference_aligned",
        target_entities="36-42",
        target_relations="30-34",
        inventory_entities_per_chunk="12-18",
        relations_per_chunk="8-12",
        focus=(
            "This is an English global-energy-system overview. Extract an English macro concept graph, not a fine-grained policy database.",
            "Current best platform shape is about 37 entities, 32 relations, and 31 attributed entities. Do not expand back to 45+ relations.",
            "The graph should look like a compact reference-style macro ontology, not a noisy extraction.",
            "Core system entities must cover exactly these macro anchors when supported: Global Energy System, Energy System, Energy Transition, Global energy transition, Fossil Fuels, Coal, Oil, Natural gas, Carbon emissions, Climate Change, Energy policy, Energy Security, Economic Activity.",
            "Renewable and low-carbon entities must cover: Renewable energy, Solar energy, Solar power, Wind energy, Hydropower, Nuclear energy, Nuclear Power, Hydrogen, Green Hydrogen, Renewable Electricity.",
            "Infrastructure and flexibility entities must cover: Electricity grids, Smart Grids, Grid Modernization, Battery technology, Batteries, Storage, Pipelines.",
            "Policy/social/economic entities must cover: Policy, Regulations, Subsidies, Regulatory frameworks, Environmental factors, International Organizations, Developed Countries, Developing Countries, Public Acceptance, Public perception, Global Economy, Earth’s Climate System.",
            "Application/sector entities must cover: Economic Activity, Hard-to-abate sectors, Steelmaking, Chemicals, Long-Distance Transport, Technology.",
            "Use canonical macro names instead of synonyms: use Storage instead of Energy Storage Technologies; Policy instead of Policy interactions; Technology instead of Technology interactions or Technological innovation; Pipelines instead of Hydrogen Infrastructure; Earth’s Climate System instead of Stability of Earth’s climate system; Global Economy instead of Future of the global economy.",
            "Prefer English relation labels from the reference-like set: powers, is_part_of, contains, drives, affects, influences, supports, enables, regulates, requires, mitigates, challenges, used_for, applies_to, optimizes.",
            "High-confidence backbone: Global Energy System powers Economic Activity; Fossil Fuels/Coal/Oil/Nuclear energy is_part_of Global Energy System; Fossil Fuels contains Coal/Oil/Natural gas; Coal/Oil/Natural gas drives Carbon emissions; Carbon emissions drives Climate Change; Climate Change influences Energy policy and drives Energy Transition; Solar energy/Wind energy/Hydropower is_part_of Renewable energy; Battery technology enables Electricity grids; Smart Grids is_part_of Electricity grids; Hydrogen enables Hard-to-abate sectors; Green Hydrogen is supported by Renewable Electricity.",
            "Also keep the reference-style macro entities: Environmental factors, Energy System, Global energy transition, Solar power. Prefer these over local risk entities such as Price volatility, Supply disruptions, Import-dependent economies, Electricity markets, or Decentralized energy production.",
            "Avoid these entities even if present in text because they hurt precision for this file: Price volatility, Supply disruptions, Uneven resource distribution, Import-dependent economies, Electricity markets, Decentralized energy production, Grid stability, Energy efficiency, Energy storage technologies, Nuclear power plants, Decarbonization, System optimization, Markets, Geopolitical tensions, Regional conflicts, Global energy markets, Trade relationships.",
            "Do not stop after the first 35 backbone relations. Continue extracting the reference-style policy, social, transition, containment, hydrogen and regulation relations until the graph has about 50-56 high-confidence relations.",
        ),
        avoid=(
            "Do not extract section titles as entities unless they are core terms.",
            "Do not create sentence-like entities such as reliable affordable scalable energy systems, gradual move away from carbon-intensive energy systems, or long-term systemic transformation.",
            "Do not over-extract every generic pressure, concern, risk, or country path unless it is a short reusable entity with relations.",
            "Avoid local risk-side branches for this file: Price volatility, Supply disruptions, Uneven resource distribution, Import-dependent economies, Electricity markets, Grid stability, Energy efficiency, Nuclear power plants.",
            "Avoid duplicate relation variants such as both Hydrogen enables Steelmaking and Hydrogen used_for Steelmaking; keep used_for for direct applications.",
        ),
        preferred_entity_types=("EnergySource", "EnvironmentalFactor", "PolicyFramework", "EconomicSector", "Technology", "GeopoliticalEntity", "SocialFactor", "concept"),
        preferred_relation_labels=("is_part_of", "drives", "influences", "contains", "regulates", "supports", "enables", "used_for", "applies_to", "powers"),
        preferred_attribute_keys=("type", "function", "Goal", "Function", "Role", "process", "Status", "Characteristics", "PrimaryUse"),
    ),
    "15": DocumentProfile(
        name="english_evolution_reference_aligned",
        target_entities="33-40",
        target_relations="17-23",
        inventory_entities_per_chunk="7-10",
        relations_per_chunk="5-8",
        focus=(
            "This is an English overview of biological evolution. Build a compact reference-style graph, not a full textbook ontology.",
            "Core anchors: Biological evolution, Organism, Last Universal Common Ancestor (LUCA), RNA World hypothesis, RNA, DNA, Proteins, Cellular structures, Environmental constraints.",
            "Evolutionary mechanisms: Natural selection, Mutation, Genetic drift, Gene flow, Adaptation, Survival, Reproduction.",
            "Major evolutionary transitions: Photosynthesis, Cyanobacteria, Great Oxidation Event, Atmospheric Oxygen, Aerobic respiration, Anaerobic Processes, Eukaryotic cells, Endosymbiotic theory, Mitochondria, Multicellularity, Cambrian Explosion.",
            "Later history anchors: Speciation, Biodiversity, Mass extinction, Mass extinction events, Mammals, Cretaceous period, Dinosaur groups, Primates, Homo sapiens, Cultural evolution, Climate change.",
            "Use stable short entity names. Preserve exact capitalization such as RNA World hypothesis, Natural selection, Eukaryotic cells, Cambrian Explosion, Homo sapiens.",
            "Prefer compact relation labels already useful for this file: drives, enables, facilitates, results_in, is_evidence_for, is_composed_of, influenced_by, occurred_during, shares_ancestry_with, causes, depends_on, evolved_from, is_more_efficient_than.",
            "High-confidence backbone: Environmental constraints drives Biological evolution; LUCA shares_ancestry_with Organism; RNA World hypothesis is_evidence_for RNA; Mutation enables Natural selection; Cyanobacteria drives Photosynthesis; Photosynthesis results_in Great Oxidation Event; Great Oxidation Event enables Aerobic respiration; Endosymbiotic theory is_evidence_for Eukaryotic cells; Oxygen levels drives Cambrian Explosion; Regulatory genes enables Cambrian Explosion; Speciation causes Biodiversity; Primates drives Homo sapiens; Cultural evolution influenced_by Biological evolution; Climate change drives Biological evolution.",
        ),
        avoid=(
            "Do not extract section titles as entities.",
            "Do not create sentence fragments such as DNA or RNA for genetic information, more stable RNA sequences, modern populations, energy conversion, life trajectory, or understanding evolution.",
            "Avoid over-expanding into every example lineage such as unicellular protists, plants, fungi, animals, Africa, habitat modification, human activity, conservation, or environmental management unless they participate in a high-confidence core relation.",
            "Avoid relation labels that are actually entity types, such as organism, concept, process, resource, phenomenon, or cellular_structure.",
        ),
        preferred_entity_types=("biological_process", "concept", "organism", "biochemical_molecule", "cellular_structure", "environmental_factor", "evolutionary_event", "scientific_theory"),
        preferred_relation_labels=("drives", "facilitates", "enables", "results_in", "is_evidence_for", "is_composed_of", "influenced_by", "occurred_during", "shares_ancestry_with", "causes", "depends_on", "evolved_from", "is_more_efficient_than"),
        preferred_attribute_keys=("function", "example", "drivers", "effect", "impact", "time", "origin", "mechanism", "nature"),
    ),
    "16": DocumentProfile(
        name="english_evolution_pdf_mechanism_aligned",
        target_entities="36-39",
        target_relations="39-43",
        inventory_entities_per_chunk="12-16",
        relations_per_chunk="10-13",
        focus=(
            "This PDF is mainly English despite Chinese notes and noisy tables. Output English entities, English types, English attributes, and English relation labels.",
            "Build a compact population-level evolution mechanism graph, not the LUCA/RNA-world history graph from file 15.",
            "Core mechanism anchors: Biological evolution, Population, Heritable variation, Genetic variation, Mutation, Natural selection, Selection pressure, Environmental conditions, DNA, Adaptation, Fitness, Genetic drift, Gene flow.",
            "Speciation and evidence anchors: Speciation, Reproductive isolation, Fossil record, Extinction, Mass extinction, Asteroid impact, Volcanic activity, Ecosystems, Common ancestor, Comparative anatomy, Molecular biology.",
            "Do not collapse evidence sources into attributes only. Comparative anatomy, Molecular biology, and Fossil record should be standalone evidence-source entities when mentioned.",
            "PDF-specific stable table anchor: keep Evolution observation batch 002 only if connected to Biological evolution or Population; do not keep batch 001 or batch 003.",
            "High-value expansion anchors should be extracted as standalone entities when explicit in the PDF: Environmental Factors, Selection Pressures, Small Populations, Geographic Barriers, Behavioral Differences, Ecological Specialization, Genetic Information, New Genetic Material, Extinction Events, Asteroid Impacts, Mass Extinction Events, Macroevolutionary Patterns.",
            "High-confidence backbone: Biological evolution operates_on Population; Heritable variation drives Biological evolution; Environmental conditions shape Heritable variation; Common ancestor explains Biological evolution; DNA carries Heritable variation; Mutation produces Genetic variation; Genetic variation occurs_in Population; Natural selection acts_on Population; Selection pressure drives Natural selection; Environmental conditions define Selection pressure; Natural selection produces Adaptation; Adaptation increases Fitness.",
            "High-confidence extension: Genetic drift changes Population; Gene flow acts_on Population; Gene flow increases Genetic variation; Gene flow counteracts Genetic drift; Reproductive isolation causes Speciation; Speciation results_from Biological evolution; Fossil record supports Biological evolution and documents Extinction; Comparative anatomy supports Common ancestor; Molecular biology supports Common ancestor; Fossil record supports Common ancestor; Asteroid impact/Volcanic activity causes Mass extinction; Mass extinction is_a Extinction; Extinction reshapes Ecosystems; Population modifies Environmental conditions.",
            "High-value expansion relations: DNA carries Genetic Information; Mutation introduces New Genetic Material; Genetic variation arises_from Mutation; Genetic variation drives Natural selection; Environmental Factors imposes Selection Pressures and defines Selection Pressures; Genetic drift depends_on Small Populations; Gene flow causes New Genetic Material; Speciation is_part_of Macroevolutionary Patterns; Fossil record supports Macroevolutionary Patterns; Macroevolutionary Patterns is_part_of Biological evolution; Extinction Events reshapes Ecosystems.",
        ),
        avoid=(
            "Do not output Chinese entity names or Chinese relation labels for this file.",
            "Do not extract PDF artifacts, page numbers, code-block markers, Mermaid graph labels, table headers, sample counts, data-entry status, or garbled strings containing Ê, 𝕏𝕐ℤ, ∮.",
            "Do not keep Evolution observation batch 001 or Evolution observation batch 003; only batch 002 is a stable explicit observation anchor.",
            "Avoid sentence-like endpoints such as central unifying concept of modern biology, differences in DNA sequences among individuals, or structured knowledge representation.",
            "Avoid file-15-specific anchors such as RNA World hypothesis, Cambrian Explosion, Eukaryotic cells, Mitochondria, Homo sapiens unless the local PDF text explicitly uses them as mechanism endpoints.",
        ),
        preferred_entity_types=("evolutionary mechanism", "biological concept", "genetic feature", "environmental factor", "evolutionary outcome", "evolutionary event", "evidence source"),
        preferred_relation_labels=("operates_on", "drives", "shape", "explains", "carries", "produces", "occurs_in", "acts_on", "define", "increases", "changes", "counteracts", "causes", "results_from", "supports", "documents", "reshapes", "modifies", "influence", "is_a"),
        preferred_attribute_keys=("function", "effect", "example", "definition", "role", "alias", "property"),
    ),
    "17": DocumentProfile(
        name="english_millennium_prize_reference_aligned",
        target_entities="38-42",
        target_relations="36-40",
        inventory_entities_per_chunk="14-20",
        relations_per_chunk="11-16",
        focus=(
            "This English document is a review-style article about the Millennium Prize Problems. Build a reference-style graph around institutions, seven problems, mathematicians, fields, theories, application domains, and the concluding historical/cultural framing.",
            "Core institution/history anchors: Clay Mathematics Institute, Landon T. Clay, Millennium Prize Problems, David Hilbert, Paris, Mathematics.",
            "Core problem anchors: P versus NP problem, P vs NP problem, Riemann Hypothesis, Navier–Stokes existence and smoothness problem, Yang–Mills existence and mass gap problem, Hodge conjecture, Birch and Swinnerton-Dyer conjecture, Poincaré conjecture.",
            "Core people/theory anchors: Bernhard Riemann, Claude-Louis Navier, George Gabriel Stokes, Chen Ning Yang, Robert Mills, Yang–Mills theory, Quantum Yang–Mills theory, Henri Poincaré, Grigori Perelman, Ricci flow with surgery.",
            "High-value expansion anchors: Computational complexity theory, Theoretical Computer Science, Cryptography, Optimization, Algorithm Design, Algebraic geometry, Number theory, Standard Model, Standard Model of particle physics, Bryan Birch, Peter Swinnerton-Dyer, Elliptic curve, Navier–Stokes Equations.",
            "Recent platform feedback shows that adding fine mathematical detail entities often lowers the package score. Do not actively chase W. V. D. Hodge, Richard Hamilton, Riemann zeta function, L-function, Prime numbers, Fluid dynamics, Quantum field theory, Topology, or Three-dimensional sphere unless the model extracts them naturally and the graph remains within the 38-42 entity / 36-40 relation target.",
            "Because the article explicitly closes with broader framing, also keep these short review-frame endpoints when present: Historical Traditions, Modern Scientific Needs, Abstract Mathematical Thinking.",
            "High-confidence backbone: Landon T. Clay founded Clay Mathematics Institute; Clay Mathematics Institute proposed/announced_by/established Millennium Prize Problems; David Hilbert influences Millennium Prize Problems; P versus NP problem belongs_to Computational complexity theory; Millennium Prize Problems is_located_in Paris for its announcement; Bernhard Riemann proposed Riemann Hypothesis; Claude-Louis Navier/George Gabriel Stokes named_after Navier–Stokes existence and smoothness problem.",
            "High-confidence extension: Chen Ning Yang/Robert Mills proposed Yang–Mills theory; Yang–Mills theory addresses Yang–Mills existence and mass gap problem and forms_foundation_of Standard Model; Hodge conjecture belongs_to Algebraic geometry; Birch and Swinnerton-Dyer conjecture belongs_to Number theory and applies_to Elliptic curve; Bryan Birch/Peter Swinnerton-Dyer formulated_by Birch and Swinnerton-Dyer conjecture; Henri Poincaré proposed Poincaré conjecture; Grigori Perelman solved_by/addresses Poincaré conjecture; Ricci flow with surgery forms_foundation_of Poincaré conjecture.",
            "For P versus NP application domains, keep both article-style impact triples and application-to-problem triples if explicitly supported by the text: Cryptography affects P versus NP problem; Optimization affects P versus NP problem; P versus NP problem affects Algorithm Design/Theoretical Computer Science.",
            "Attributes matter for this file: give concise distinguishing attributes for named problems and people, such as field_of_study, proposer, year, status, location, role, related_problem, object, or application. Attribute values must be short.",
        ),
        avoid=(
            "Do not create endpoints from long explanatory clauses such as whether P is equal to NP, distribution of prime numbers, one million US dollars, technical difficulty, theoretical mathematics, or boundaries of current mathematical understanding.",
            "Do not extract long generic cultural phrases such as targets for resolution, guiding landmarks for mathematical exploration, living discipline, broader intellectual discourse, or enduring mystery of mathematics.",
            "Avoid noisy duplicate entities such as Perelman, Perelman’s proof, Clay problem, mathematical community, mass gap phenomenon, Three-sphere, or Simply connected closed three-dimensional manifold unless needed for a core relation.",
            "Do not add the full fine-detail set around Riemann zeta function, L-function, Prime numbers, Fluid dynamics, Quantum field theory, Topology, Three-dimensional sphere, W. V. D. Hodge, and Richard Hamilton by default; this expansion previously reduced score.",
        ),
        preferred_entity_types=("person", "mathematical_problem", "scientific_field", "theory", "organization", "location", "mathematical_object"),
        preferred_relation_labels=("founded", "proposed", "established", "announced_by", "belongs_to", "is_part_of", "contains", "applies_to", "affects", "influences", "named_after", "addresses", "forms_foundation_of", "forms_the_foundation_of", "formulated_by", "proposed_by", "solved_by", "located_in", "is_located_in", "originates_from"),
        preferred_attribute_keys=("full_name", "field_of_study", "Field", "Proposer", "application", "role", "related_problem"),
    ),
    "18": DocumentProfile(
        name="english_greek_mythology_reference_precision",
        target_entities="no fixed cap; extract only stable competition-worthy entities",
        target_relations="no fixed cap; prefer high-confidence core triples over narrative detail",
        inventory_entities_per_chunk="8-16",
        relations_per_chunk="6-12",
        focus=(
            "This English document is a Greek mythology relationship narrative. Extract a precision-oriented reference graph, not a full narrative event graph.",
            "Core anchors that should be favored: Zeus, Cronus, Hera, Athena, Apollo, Artemis, Demeter, Hades, Persephone, Moirai, Clotho, Lachesis, Atropos, Heracles, Alcmene, Cerberus, Nemean Lion, Achilles, Peleus, Thetis, Trojan War, Paris, Helen, Troy, Mount Olympus, Delphi, Athens, Odysseus, fate.",
            "Use additional named entities only if they support a very stable relation and are not merely narrative scenery. Do not automatically expand every named place, sibling, underworld item, or war participant.",
            "High-value relations are explicit parent/child, spouse, ruler/residence, patronage, twin-sibling, membership in Moirai, captured/slayed, and core Trojan War involvement.",
            "Keep entity names short and canonical. Put domains such as goddess of wisdom, god of the sea, queen of the gods, or ferryman into attributes, not into the name.",
        ),
        avoid=(
            "Do not create entities from generic words or relation phrases: gods, mortals, causes, governs, guides souls, plays role in, resides in, rules over, wilderness, mortal affairs, conflict, land, winter, twelve labors.",
            "Do not create long descriptive endpoints such as sanctity of marriage, hidden realms beyond, balance between civilization and nature, intelligence and endurance, natural world, human condition.",
            "Avoid low-granularity narrative expansion that previously reduced platform score: Agamemnon, Hector, Hestia, Poseidon, Styx, Tartarus, Trojan Horse, Underworld, sea, souls, Greek forces, walls.",
            "Do not add many sibling/domain/scenery triples. If a relation is not central to the reference graph, omit it even if the sentence is explicit.",
            "Do not use entity categories as relation labels. Use short predicates such as parent_of, son_of, ruler_of, resides_in, patron_deity_of, involved_in, captured_by, killed, spouse_of.",
        ),
        preferred_entity_types=("deity", "titan", "hero", "mortal", "location", "creature", "war", "group", "concept"),
        preferred_relation_labels=("parent_of", "son_of", "daughter_of", "spouse_of", "sibling_of", "twin_sister_of", "ruler_of", "rules", "resides_in", "patron_deity_of", "associated_with", "involves", "caused_by", "abducted_by", "captured_by", "killed", "is_part_of", "guides", "crosses", "located_in", "prince_of"),
        preferred_attribute_keys=("domain", "role", "title", "type", "location", "Roman_name", "status", "symbol"),
    ),
    "19": DocumentProfile(
        name="english_blockchain_aurorachain_compact_architecture",
        target_entities="32-38; compact system architecture entities only",
        target_relations="45-52; compact module/data/governance triples",
        inventory_entities_per_chunk="12-22",
        relations_per_chunk="10-18",
        focus=(
            "This English document describes the AuroraChain permissioned blockchain system. Extract a compact system architecture graph, not a sentence-by-sentence event graph and not a generic blockchain glossary.",
            "Core component anchors: AuroraChain Network, NovaTech Labs, Distributed Ledger, Validator Nodes, Proof of Authority, Proof of Authority consensus mechanism, AuroraToken, Smart Contracts, Contract Deployment Module, Digital Identities, Digital Identity, Identity Management System, Transaction Pool, Cross-Chain Gateway, Governance Committee, Governance Smart Contracts, Monitoring Service, API Gateway, Audit Nodes.",
            "Accepted compact data/operation endpoints: On-Chain Data, Off-Chain Data, Transaction Records, Relayer Services, Regulatory bodies, Independent Auditors, Enterprise, cryptographic hashes, permissioned blockchain, unconfirmed transactions, new blocks, pay transaction fees, premium network services, submit transactions, full copy of the Distributed Ledger, network activity.",
            "High-value relations are explicit composition, usage, integration, validation, storage, monitoring, governance, deployment, operation, and data-reference relations.",
            "Keep entity names canonical and short. Put properties such as transparency, immutability, accountability, deterministic behavior, auditability, and decentralization into attributes rather than entities.",
        ),
        avoid=(
            "Do not create abstract quality entities: transparency, immutability, accountability, efficiency, governance, security, trust, operational friction, centralized intermediaries, next-generation digital infrastructure.",
            "Do not create long sentence endpoints or vague process endpoints: automate settlement processes, establish trust across organizational boundaries, balance decentralization efficiency governance and security.",
            "Do not extract fine-grained endpoints that reduced score in prior submissions: Monetary Policy, Core Protocol, Asset Transfer Contract, Cryptographic Proofs, External blockchain systems, asset transfers, data exchange, external applications, developers, blockchain data, cryptographic keys, verifiable credentials, alerts, anomalies, Smart Contract States, Governance Decisions.",
            "Prefer compact architecture relation labels such as contains, composed_of, integrates, uses, utilizes, operates, manages, governs, implements, facilitates, analyzes, interacts_with, operated_by.",
        ),
        preferred_entity_types=("software_component", "infrastructure", "interface", "digital_asset", "governance_body", "Data", "organization", "concept"),
        preferred_relation_labels=("integrates", "operates", "uses", "utilizes", "composed_of", "manages", "contains", "used_for", "operated_by", "stores", "temporarily_stores", "validates", "monitors", "packages", "follows", "relies_on", "references", "analyzes", "interacts_with"),
        preferred_attribute_keys=("function", "type", "role", "purpose", "storage_location", "examples", "example"),
    ),
    "20": DocumentProfile(
        name="english_quantum_theory_compact",
        target_entities="28-34",
        target_relations="28-38",
        inventory_entities_per_chunk="10-16",
        relations_per_chunk="8-12",
        focus=(
            "This English document is a compact history and concept overview of quantum theory.",
            "Keep canonical anchors: Quantum Theory, quantum mechanics, Max Planck, Planck Constant, Black-Body Radiation, Albert Einstein, Photoelectric Effect, Photon, Niels Bohr, Bohr Model of the Atom, Werner Heisenberg, Erwin Schrödinger, Matrix Mechanics, Wave Mechanics, Schrödinger's Equation, Wave Function, Max Born, probabilistic interpretation of quantum mechanics, Uncertainty Principle, superposition, wave function collapse, Copenhagen interpretation, many-worlds interpretation, quantum entanglement, qubit, quantum computing, quantum cryptography, quantum communication.",
            "Prefer compact relation labels around introduced_by, contributed_to, part_of, led_to, developed, formulated_by, governs_system, uses, interpretation_of, applies_to.",
        ),
        avoid=(
            "Do not create entities from generic philosophical phrases: reality, determinism, role of the observer, philosophical questions, intuitive understanding, emerging technologies.",
            "Do not create explanation phrase endpoints such as correlations between particles, particle-like behavior of electromagnetic radiation, microscopic scales, or fundamental interactions.",
            "Avoid duplicate casing and OCR-like names: Dinger’s equation, Quantum mechanics/quantum mechanics duplicates, Bohr model/Bohr Model of the Atom duplicates.",
        ),
        preferred_entity_types=("researcher", "Concept", "physical_phenomenon", "technological_application", "mathematical_concept", "Theory", "Interpretation"),
        preferred_relation_labels=("developed_by", "formalized_by", "contains", "governs_system", "relates_to", "developed", "interprets", "contributed_to"),
        preferred_attribute_keys=("contribution", "function", "nature", "domain", "symbol", "achievement", "proposer", "usage"),
    ),
    "21": DocumentProfile(
        name="english_conspiracy_0609_platform",
        target_entities="29-31",
        target_relations="31-33",
        inventory_entities_per_chunk="8-14",
        relations_per_chunk="7-12",
        focus=(
            "Package-level feedback shows the strongest submitted packages keep this file at about 30 entities and 32 relations, not the shorter claim-safe graph.",
            "Preserve the reference mixed-name style instead of over-cleaning: Conspiracy theories, Conspiracy theory, Moon landing hoax, Apollo 11 mission, Moon landing, United States government, U.S. government, Soviet Union, Assassination of John F. Kennedy, John F. Kennedy assassination, Lee Harvey Oswald, CIA, Mafia, Illuminati, September 11 attacks, September 11, 2001 terrorist attacks, 9/11 conspiracy theories, Internet, Social media, Official narratives, Distrust of authority, human desire for alternative explanations, Texas School Book Depository, flat Earth, public opinion, power, truth, Celebrity deaths.",
            "Use broad platform relation labels when supported: challenges, is attributed to, is associated with, originates from, is fueled by, contains, is_part_of, affects, supports, causes, drives.",
            "Keep both event variants when they appear in model output: Assassination of John F. Kennedy and John F. Kennedy assassination; September 11 attacks and September 11, 2001 terrorist attacks.",
        ),
        avoid=(
            "Do not over-correct into a fact-safe ontology with Moon landing hoax theory, controlled demolitions, World Trade Center, Pentagon, and many precise claim nodes.",
            "Do not collapse Conspiracy theories and Conspiracy theory into one node; the platform-style package kept both.",
            "Do not rewrite legacy weak labels into scholarly labels if that changes endpoint matching.",
        ),
        preferred_entity_types=("conspiracy_theory", "historical_event", "organization", "person", "place", "communication_platform", "social_phenomenon"),
        preferred_relation_labels=("challenges", "is attributed to", "is associated with", "originates from", "is fueled by", "contains", "is_part_of", "affects", "supports", "causes", "drives"),
        preferred_attribute_keys=("Year", "year", "date", "location", "role", "Role", "origin", "impact", "function", "alias"),
    ),
    "22": DocumentProfile(
        name="english_fashion_balanced",
        target_entities="60-66",
        target_relations="20-26",
        inventory_entities_per_chunk="8-14",
        relations_per_chunk="5-9",
        focus=(
            "Fashion periods, materials, trends, cultural/technological drivers.",
            "Current best platform shape is about 64 entities, 23 relations, and 60 attributed entities. This file rewards many short period/person/trend attributes, not dense relation expansion.",
            "Preserve title/case-sensitive period names when explicit: 1950s Fashion, 1960s-70s Fashion, 1980s-90s Fashion, 21st Century Fashion, Millennium Fashion, Great Depression of the 1930s.",
            "Prefer short attributes for period, key_influencer, material, style, role, technology, or impact.",
        ),
        preferred_entity_types=("historical_period", "social_group", "fashion_element", "media_platform", "concept", "Process", "influencing_factor", "industry_sector"),
        preferred_relation_labels=("evolved_during", "popularized_by", "reflected_in", "gained_traction", "shaped_by", "applies_to", "shapes", "emphasizes"),
        preferred_attribute_keys=("concept", "process", "role", "impact", "material", "locations", "key_influencer", "key_technology"),
    ),
    "23": DocumentProfile(
        name="english_autonomous_vehicle_balanced",
        target_entities="30-32",
        target_relations="21-25",
        inventory_entities_per_chunk="7-12",
        relations_per_chunk="7-12",
        focus=("Autonomous vehicles, sensors, AI algorithms, safety, regulation, transportation impacts.",),
        preferred_entity_types=("stakeholder", "challenge", "component", "benefit", "technology", "transportation_mode", "Organization", "infrastructure"),
        preferred_relation_labels=("affects", "utilizes", "addresses", "faces", "invests_in", "enables", "improves", "requires", "increases", "applies_to"),
        preferred_attribute_keys=("function", "role", "alias", "status", "impact", "key_issues", "primary_function", "key_feature"),
    ),
    "24": DocumentProfile(
        name="english_coral_reef_0609_platform",
        target_entities="29-31",
        target_relations="34-36",
        inventory_entities_per_chunk="8-14",
        relations_per_chunk="8-13",
        focus=(
            "Package-level feedback shows this file should be a 30-entity, 35-relation platform-style ecosystem graph, not the smaller semantic-cleanup version.",
            "Preserve the reference mixed casing and granularity: Coral reefs, Coral polyps, Marine life, Coastal communities, Coastal protection, Fisheries, Natural disasters, Sustainable fisheries, Tourism, Climate change, Pollution, Marine protected areas, Greenhouse gas emissions, marine biodiversity, ecosystem services, human activities, environmental stressors, conservation and sustainable management, Biodiversity, Human Well-being, Local Economies, Coral Bleaching, Tourism Industry, Fish, Storms, Fishing, Overfishing, Ocean Ecosystems, Calcium Carbonate, Ocean Acidification.",
            "Prefer relation labels from the reference package: contributes_to, is_habitat_for, protects, provides, mitigates, relies_on, supports, threatens, impacts, contains, is_part_of, affects, causes.",
            "Keep broad service/threat relations even when they look less elegant, such as Coral reefs supports Fishing, Coral reefs affects Storms, and Coral reefs contains Fish.",
        ),
        avoid=(
            "Do not switch to the previously failed lowercase semantic graph with only 23-26 entities.",
            "Do not split Marine life into Invertebrates and Plants; the stable package kept Fish only as a broad endpoint.",
            "Do not add future generations, urgent action, fragile habitats, conservation efforts, water quality, or many detailed conservation-policy nodes.",
            "Do not force every threat relation to the clean label threatens if the reference style uses impacts, affects, or causes.",
        ),
        preferred_entity_types=("human_activity", "organism", "environmental_factor", "ecosystem_service", "conservation_measure", "ecosystem", "Concept"),
        preferred_relation_labels=("contributes_to", "is_habitat_for", "protects", "provides", "mitigates", "relies_on", "supports", "threatens", "impacts", "contains", "is_part_of", "affects", "causes"),
        preferred_attribute_keys=("function", "Function", "status", "Benefit", "benefit", "impact", "effect", "source", "goal"),
    ),
    "25": DocumentProfile(
        name="english_fairytale_origin_versions",
        target_entities="19-25",
        target_relations="15-20",
        inventory_entities_per_chunk="9-13",
        relations_per_chunk="8-12",
        focus=(
            "This English PDF is about the origins and versions of famous fairytales.",
            "Keep the graph centered on tale titles, collectors/authors, source traditions, and a few explicit story characters or motifs.",
            "Preferred endpoints: Fairytales, Grimm's Fairy Tales, Brothers Grimm, Jacob Grimm, Wilhelm Grimm, German countryside, oral traditions, Cinderella, Rhodopis, ancient Greece, Charles Perrault, fairy godmother, glass slipper, Snow White, evil queen, seven dwarfs, Hansel and Gretel, cannibalistic witch, European folklore, Beauty and the Beast, ancient myths, Ovid, Pygmalion and Galatea, Love and Transformation.",
            "Use source/version relations precisely: Grimm's Fairy Tales contains tales; Brothers Grimm collected/published tales; Cinderella has_version_by Charles Perrault and originated_from Rhodopis/ancient Greece; Snow White originated_from German folklore; Hansel and Gretel originated_from European folklore; Beauty and the Beast inspired_by Pygmalion and Galatea.",
        ),
        avoid=(
            "Do not output Fairytales authored_by Brothers Grimm. The Brothers Grimm collected and published a collection; they did not author all fairytales.",
            "Do not say Beauty and the Beast was collected_by Brothers Grimm unless the text explicitly says so; this document traces it to ancient myths and Ovid's Pygmalion and Galatea.",
            "Do not use relation endpoints that are publication containers as people, such as Cinderella published_in Charles Perrault or Ovid authored_by Pygmalion and Galatea.",
            "Do not create many generic theme entities such as magical elements, heroic protagonists, moral lessons unless they form central relations.",
        ),
        preferred_entity_types=("person", "literary work", "Character", "collection", "cultural tradition", "mythological figure", "Object", "Theme"),
        preferred_relation_labels=("contains", "collected_by", "collected_in", "published_by", "published_in", "originated_from", "has_version_by", "introduced", "features_character", "inspired_by", "wrote_about", "part_of"),
        preferred_attribute_keys=("genre", "nationality", "profession", "function", "authors", "publication_era", "origin", "earliest_origin", "notable_author"),
    ),
}

DISABLED_PROFILE_STEMS = set()


FINAL_ROUND_PROFILES: dict[str, DocumentProfile] = {
    "1": DocumentProfile(
        name="final_jurassic_high_recall",
        target_entities="130-155",
        target_relations="115-145",
        inventory_entities_per_chunk="28-42",
        relations_per_chunk="24-38",
        focus=(
            "复赛文件1是侏罗纪地质、生物演化和古生态长文，应抽成高召回地质古生物图谱。",
            "优先覆盖地质时期、古地理大陆/海洋、气候阶段、恐龙分类、代表恐龙、植物类群、海洋爬行动物、翼龙、哺乳动物、化石地点、研究人物、地层划分和灭绝/界线事件。",
            "关系要密集覆盖属于、早于/晚于、开始于、结束于、名称源自、分裂为、形成于、包括、生活在、发现于、研究、影响等。",
            "属性可补英文名、时间范围、生存年代、食性、体长、化石产地、代表特征，值保持短。"
        ),
        avoid=("不要把博物馆闲聊、拍照、讲解员口语和完整句子当实体。",),
    ),
    "2": DocumentProfile(
        name="final_mechanics_high_recall",
        target_entities="120-145",
        target_relations="105-130",
        inventory_entities_per_chunk="26-40",
        relations_per_chunk="22-36",
        focus=(
            "复赛文件2是力学发展综述，应覆盖力学分支、核心定律、物理量、数学形式、代表人物和现代扩展。",
            "优先抽经典力学、静力学、分析力学、连续介质力学、相对论力学、量子力学、牛顿定律、守恒定律、拉格朗日/哈密顿体系、动量/能量/力/质量/加速度等物理量。",
            "关系要覆盖包括、提出、建立、奠基、关联、由、属于、联系、适用于、修正等。",
            "属性优先补符号、单位、定义、代表形式、贡献、著作。"
        ),
    ),
    "3": DocumentProfile(
        name="final_cosmology_high_recall",
        target_entities="105-125",
        target_relations="85-105",
        inventory_entities_per_chunk="24-36",
        relations_per_chunk="18-30",
        focus=(
            "复赛文件3是宇宙形成史，从神话到现代宇宙学，应覆盖理论、证据、人物、观测、模型和关键事件。",
            "优先抽创世神话、日心说、广义相对论、宇宙常数、膨胀宇宙解、哈勃定律、大爆炸理论、宇宙微波背景、暴胀理论、暗物质、暗能量等。",
            "关系覆盖提出、发现、支持、否定、解释、导致、观测到、属于、影响。"
        ),
    ),
    "4": DocumentProfile(
        name="final_expert_system_dense",
        target_entities="75-90",
        target_relations="72-90",
        inventory_entities_per_chunk="22-34",
        relations_per_chunk="20-32",
        focus=(
            "复赛文件4是专家系统和知识工程，应覆盖系统组成、推理机制、知识表示、应用场景、优势局限和发展演进。",
            "核心实体包括知识库、推理机、解释模块、人机接口、规则、事实、产生式规则、正向推理、反向推理、不确定性推理、MYCIN、DENDRAL、知识工程等。",
            "关系尽量让组件和方法互联：包含、使用、依赖、解释、应用于、解决、支持、限制。"
        ),
    ),
    "5": DocumentProfile(
        name="final_industrial_engineering_dense",
        target_entities="88-105",
        target_relations="82-100",
        inventory_entities_per_chunk="24-36",
        relations_per_chunk="20-32",
        focus=(
            "复赛文件5是工业工程发展与方法体系，应覆盖人物、方法、流程、质量、物流、智能制造和系统优化。",
            "优先抽泰勒、吉尔布雷斯夫妇、科学管理、动作研究、方法研究、作业测定、生产计划与控制、质量管理、设施规划、物流分析、精益生产、六西格玛、智能制造等。",
            "关系覆盖提出、创立、包括、用于、优化、降低、提高、支撑、应用于。"
        ),
    ),
    "6": DocumentProfile(
        name="final_ai_data_semantics_dense",
        target_entities="85-100",
        target_relations="75-90",
        inventory_entities_per_chunk="22-34",
        relations_per_chunk="18-30",
        focus=(
            "复赛文件6讨论AI时代数据含义，应覆盖事实层、语义层、关系层、意图层、行动层、数据质量、知识库、模型、流程闭环和治理。",
            "关系重点覆盖回答、要求、依赖、连接、影响、联动、解释、用于、形成闭环、支撑。",
            "属性少量补定义、作用、要求和风险。"
        ),
    ),
    "7": DocumentProfile(
        name="final_blockchain_high_recall",
        target_entities="115-135",
        target_relations="105-130",
        inventory_entities_per_chunk="26-40",
        relations_per_chunk="22-36",
        focus=(
            "复赛文件7是区块链技术综述，应覆盖分布式账本、区块结构、密码学、共识机制、比特币、以太坊、智能合约、预言机、应用和风险。",
            "优先抽区块、区块头、区块体、前一区块哈希、时间戳、默克尔根、哈希函数、非对称加密、数字签名、私钥、公钥、PoW、PoS、联盟链、BFT、UTXO、DeFi、NFT、DAO、预言机等。",
            "关系要接近实体数：包含、记录、生成、验证使用、包括、维护、支持、依赖、带来风险、应用于。"
        ),
    ),
    "8": DocumentProfile(
        name="final_dermatology_dense",
        target_entities="88-105",
        target_relations="86-105",
        inventory_entities_per_chunk="24-36",
        relations_per_chunk="22-34",
        focus=(
            "复赛文件8是常见皮肤问题和用药治理，应覆盖器官功能、非感染性疾病、感染性疾病、症状、诱因、药物类别和就医警示。",
            "优先抽湿疹、特应性皮炎、接触性皮炎、荨麻疹、痤疮、脂溢性皮炎、真菌感染、足癣、银屑病、带状疱疹、抗组胺药、外用维A酸、抗真菌药等。",
            "关系覆盖表现为、诱发、治疗、需要、属于、包括、避免、修复。"
        ),
    ),
    "9": DocumentProfile(
        name="final_video_games_high_recall",
        target_entities="150-180",
        target_relations="135-160",
        inventory_entities_per_chunk="30-46",
        relations_per_chunk="26-42",
        focus=(
            "复赛文件9是电子游戏文化、技术、产业和类型系统长文，应抽取最高召回密度。",
            "优先覆盖类型系统、规则/目标/体验、游戏引擎、图形技术、网络技术、人工智能、规则系统、反馈机制、玩家动机、开发/发行/运营/平台方、玩家社群、电竞、直播、独立游戏、移动游戏、VR/AR等。",
            "关系覆盖经历、进入、包含、组合、核心技术包括、设计方法包括、产业环节包括、使用、推动、影响、形成。"
        ),
    ),
    "10": DocumentProfile(
        name="final_rainfall_process_dense",
        target_entities="80-95",
        target_relations="90-110",
        inventory_entities_per_chunk="22-34",
        relations_per_chunk="24-38",
        focus=(
            "复赛文件10是降雨形成过程，应抽成过程链和机制图。",
            "优先覆盖水汽、水循环、蒸发、蒸腾、水汽输送、凝结、降水、空气抬升、绝热冷却、凝结核、云滴、冰晶、暖云/冷云降雨机制、碰并增长、冰晶过程和降雨类型。",
            "关系要覆盖需要、属于、包括、导致、依赖、形成、核心过程、影响。"
        ),
    ),
    "11": DocumentProfile(
        name="final_food_nutrition_high_recall",
        target_entities="135-160",
        target_relations="120-145",
        inventory_entities_per_chunk="28-42",
        relations_per_chunk="24-38",
        focus=(
            "复赛文件11是食品与营养学长文，应覆盖营养素、食物来源、生理作用、加工方式、营养成分表和健康目标。",
            "优先抽碳水化合物、脂肪、蛋白质、维生素、矿物质、膳食纤维、肠道菌群、短链脂肪酸、加工方式、过度加工食品、营养成分表等。",
            "关系覆盖提供、来源于、包括、消化为、影响、促进吸收、参与、产生、标示。"
        ),
    ),
}

for _stem, _counts in {
    "12": ("48-60", "48-60", "Urban legends, folklore, origins, themes, spread, technology, society."),
    "13": ("44-55", "44-55", "AI ethics, privacy, bias, accountability, transparency, social impact, governance."),
    "14": ("54-64", "52-62", "Bees, pollination, crops, ecosystems, threats, conservation, sustainable farming."),
    "15": ("52-62", "50-60", "Space exploration history, missions, agencies, companies, Mars, future technology."),
    "16": ("54-64", "52-62", "Magic tricks history, magicians, periods, illusions, props, entertainment."),
    "17": ("50-60", "48-58", "Cooking chemistry, Maillard reaction, emulsification, acids, salts, temperature, preservation."),
    "18": ("54-64", "50-60", "Board games history, ancient games, regions, periods, technology, social role."),
    "19": ("70-82", "68-80", "Rocket building process, purpose, design, materials, assembly, testing, launch, physics."),
    "20": ("66-78", "56-66", "Coffee history, culture, society, coffee houses, economy, production, sustainability."),
    "21": ("52-62", "50-60", "Sports, culture, shared experiences, values, social change, economy, identity."),
    "22": ("58-68", "54-64", "Language death, language shift, intergenerational transmission, migration, preservation."),
    "23": ("64-74", "62-72", "Fire in human history, warmth, cooking, technology, culture, industry."),
    "24": ("54-64", "52-62", "Human cloning ethics, identity, exploitation, sanctity of life, medicine, regulation."),
    "25": ("64-74", "62-72", "Pop culture, global trends, fashion, music, technology, social values, criticism."),
}.items():
    FINAL_ROUND_PROFILES[_stem] = DocumentProfile(
        name=f"final_english_{_stem}_dense",
        target_entities=_counts[0],
        target_relations=_counts[1],
        inventory_entities_per_chunk="14-22",
        relations_per_chunk="12-20",
        focus=(
            f"Final-round English essay topic: {_counts[2]}",
            "Use a dense but clean graph: central topic, categories, causes, effects, examples, historical stages, people/organizations/places, risks, benefits, and preservation or governance actions.",
            "Prefer roughly one relation per important entity. Do not leave core entities isolated.",
            "Use source wording for entity names. Keep common lowercase essay terms when they are the source's natural wording.",
            "Short attributes are useful for definition, role, origin, function, example, impact, period, and status."
        ),
        avoid=(
            "Do not create very long clause-like endpoints.",
            "Do not turn every adjective or generic value word into an entity.",
            "Avoid over-normalizing all relation labels into a tiny set; keep clear source-like predicates when concise."
        ),
        preferred_entity_types=("Concept", "Domain", "Process", "Historical period", "Example", "Actor", "Impact", "Risk", "Practice", "Technology"),
        preferred_relation_labels=("include", "includes", "uses", "requires", "affects", "influences", "supports", "causes", "leads to", "part of", "traced to", "spread by", "plays role in"),
        preferred_attribute_keys=("definition", "role", "origin", "function", "example", "impact", "period", "status", "purpose"),
    )


def get_document_profile(stem: str, language: str) -> DocumentProfile:
    if str(stem) in DISABLED_PROFILE_STEMS:
        return DEFAULT_ZH_PROFILE if language == "zh" else DEFAULT_EN_PROFILE
    return PROFILES.get(str(stem), DEFAULT_ZH_PROFILE if language == "zh" else DEFAULT_EN_PROFILE)


def get_final_round_profile(stem: str, language: str) -> DocumentProfile:
    return FINAL_ROUND_PROFILES.get(str(stem), DEFAULT_ZH_PROFILE if language == "zh" else DEFAULT_EN_PROFILE)
